#Price for /asc get
ChestPrice: 100
#How many block up do you want to place plugin hologram
HologramHeight: 3.5
#In how many seconds do you want to sell items to market
SellInterval: 1800
#In how many seconds do you want to update hologram countdown
IntervalHoloReplacer: 15
#In how many seconds do you want to save data to data file
DataSaveInterval: 30
#Creates particles besides chest
#Currently disabled
UseParticles: true
ParticleDelayPerTick: 2
#You can set these sounds '' to disable them
#If you are using this plugin on 1.8
#You have to change these sounds.
MoneyCollectedSound: 'ENTITY_PLAYER_LEVELUP'
CreatedChestSound: 'ENTITY_PLAYER_LEVELUP'
DeletedChestSound: 'ENTITY_VILLAGER_HURT'
ClosedManageItemsMenuSound: 'ENTITY_PLAYER_LEVELUP'
StartSellingSoundSound: 'ENTITY_PLAYER_LEVELUP'
StopSellingSound: 'ENTITY_VILLAGER_HURT'
NoSpaceSound: 'ENTITY_VILLAGER_HURT'
#You can use Essentials or ShopGUIPlus or Custom for now.
#You can edit Essentials prices in Essentials/worth.yml
#You can edit ShopGUIPlus prices in ShopGUIPlus/shops/shop.yml
#You can edit Custom prices in below
PriceSource: Essentials
CustomPrices:
  DIAMOND:
    Price: 100
  IRON_INGOT:
    Price: 50