name: AutoSellChest
version: '${project.version}'
main: me.waterarchery.autosellchest.AutoSellMain
api-version: 1.13
depend: [ Vault ]
softdepend: [ DecentsHolograms, HolographicDisplays, Essentials, ShopGUIPlus ]
authors: [ WaterArchery ]
description: Sells items into market in the specific chest
commands:
  asc:
    description: Main command for Auto Sell Chest plugin
    aliases:
      - autosellchest
      - aschest
permissions:
  asc.admin.*:
    default: op
    description: Admin permissions for auto sell chest
    children:
      asc.remove.player: true
